En Python, implemente una clase para solucionar sistemas lineales. El constructor de clase
deber recibir la matriz y el vector independiente. El primer método de clase resuelve el
sistema usando el método de Jacobi, y el segundo método resuelve el sistema usando el
método de Gauss-Seidel. En la pantalla debe aparecer el número de iteraciones necesarias
para resolver el problema.

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [40]:
class SolveLinEquations:
    def __init__(self, Matrix, Vector_i):
        self.m = Matrix
        self.v = Vector_i
    def JacobiMethod(self,itmax=1000,error = 1e-10):
        A= self.m
        b= self.v
        m,n = A.shape
        x = np.zeros(n)
    
        sumk = np.zeros_like(x)

        x = [13,20,-1]

        it = 0

        residuo = np.linalg.norm( b - np.dot(A,x) )

        while ( residuo > error and it < itmax ):

            it += 1

            for i in range(m):
                sum_ = 0
                for j in range(n):
                    if i != j:
                        sum_ += A[i][j]*x[j]
                sumk[i] = sum_

            for i in range(m):

                if A[i,i] != 0:
                    x[i] = (b[i] - sumk[i])/A[i,i]
                else:
                    print('No invertible con Jacobi')
            print("iteración numero "+str(it)+":")
            print(x)
            residuo = np.linalg.norm( b - np.dot(A,x) )
        return x,it,residuo
    
    def Gauss_Seidel(self,max_iter=1000,tolerancia=1e-10):
        A= self.m
        B= self.v
        tam = np.shape(A)
        n = tam[0]
        m = tam[1]
        x_0 = np.array([0,0,0])
        #V_iniciales
        X = np.copy(x_0)
        v_dif = np.ones(n,dtype=float)
        errado = 2*tolerancia
        it = 0
        while not(errado<=tolerancia or it>max_iter):
            for i in range(0,n):
                suma = 0
                for j in range(0,n):
                    if (j != i):
                        suma += (A[i,j]*X[j])
                act = (B[i]-suma)/(A[i,i])
                v_dif[i]=np.abs(act-X[i])
                X[i] = act
            errado=np.max(v_dif)
            it += 1
            print("iteración numero "+str(it)+":")
            print(X)
            residuo = np.linalg.norm( B - np.dot(A,X) )
        if it>max_iter:
            X=0
            print("No se logro la convergencia del sistema de ecuaciones")
        return X,it,residuo

In [41]:
M = np.array([[3,-1,-1],[-1.,3.,1.],[2,1,4]])
b = np.array([1.,3.,7.])
eq = SolveLinEquations(M,b)

In [42]:
x,it,residuo=eq.Gauss_Seidel()

iteración numero 1:
[0 1 1]
iteración numero 2:
[1 1 1]
iteración numero 3:
[1 1 1]


In [43]:
x_j,it_j,residuo_j=eq.JacobiMethod()

iteración numero 1:
[6.666666666666667, 5.666666666666667, -9.75]
iteración numero 2:
[-1.0277777777777777, 6.472222222222222, -3.0]
iteración numero 3:
[1.4907407407407407, 1.6574074074074074, 0.6458333333333333]
iteración numero 4:
[1.10108024691358, 1.2816358024691359, 0.5902777777777777]
iteración numero 5:
[0.9573045267489713, 1.170267489711934, 0.879050925925926]
iteración numero 6:
[1.0164394718792866, 1.0260845336076818, 0.9787808641975309]
iteración numero 7:
[1.0016217992684042, 1.012552869227252, 0.9852591306584362]
iteración numero 8:
[0.9992706666285628, 1.0054542228699894, 0.9960508830589849]
iteración numero 9:
[1.0005017019763247, 1.0010732611898592, 0.9990011109682213]
iteración numero 10:
[1.0000247907193602, 1.0005001970027012, 0.9994808337143728]
iteración numero 11:
[0.9999936769056914, 1.0001813190016626, 0.9998625553896445]
iteración numero 12:
[1.0000146247971025, 1.0000437071720156, 0.9999578317967386]
iteración numero 13:
[1.0000005129895848, 1.000018931000121

In [30]:
x

array([1, 1, 1])

In [31]:
x_j

[1.0000000000012628, 1.0000000000109328, 0.9999999999902489]