Implemente un algoritmo que realice la multiplicación de dos matrices. Use el algoritmo
para calcular:
$$\mathbb{AB}=\begin{pmatrix}
1 & 0 & 0\\ 
5 & 1 & 0\\ 
-2 & 3 & 1
\end{pmatrix}\begin{pmatrix}
4 & -2 & 1\\ 
0 & 3 & 7\\ 
0 & 0 & 2
\end{pmatrix}$$

In [1]:
import numpy as np

In [26]:
def Solve_mult_matrix(A,B):
    N=A.shape
    M=B.shape
    if N[1]==M[0]:
        res=np.zeros((N[0],M[1]),dtype = int)
        for i in range(N[0]): 
            for j in range(M[1]):
                for k in range(len(B)):
                    res[i, j] += A[i, k] * B[k, j]
    else:
        res= "estas matrices no pueden ser multiplicadas"
    return res

In [27]:
A = np.array([[1,0,0],[5,1,0],[-2,3,1]])
B = np.array([[4,-2,1],[0,3,7],[0,0,2]])
print(f"Matrix A:\n {A}\n")
print(f"Matrix B:\n {B}\n")


Matrix A:
 [[ 1  0  0]
 [ 5  1  0]
 [-2  3  1]]

Matrix B:
 [[ 4 -2  1]
 [ 0  3  7]
 [ 0  0  2]]



In [28]:
res=Solve_mult_matrix(A,B)
print(f"Matris resultante AB:\n {res}\n")

Matris resultante AB:
 [[ 4 -2  1]
 [20 -7 12]
 [-8 13 21]]

